spring:
  application:
    name: portugease-api

  datasource:
    url: ${PORTUGEASE_DB_URL:jdbc:postgresql://localhost:5432/portugease}
    username: ${PORTUGEASE_DB_USERNAME:postgres}
    password: ${PORTUGEASE_DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: ${PORTUGEASE_API_PORT:8080}